services:
  sglang-server:
    #image: lmsysorg/sglang:v0.5.16-cu130-runtime
    image: lmsysorg/sglang:qwen38-27b
    restart: "no"
    ipc: host
    tty: true
    ports:
      - "30000:30000"
    volumes:
      - /mnt/hg_cache/huggingface:/root/.cache/huggingface
      - /mnt/asus_card:/mnt/asus_card
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all      # 这里改成了 all，自动映射宿主机的所有 GPU
              capabilities: [gpu]
    command: >
      python3 -m sglang.launch_server
        --host 0.0.0.0 --port 30000
        --tp 4 --mem-fraction-static 0.94
        --attention-backend flashinfer
        --cuda-graph-max-bs-decode 4
        --max-running-requests 4
        --max-total-tokens 262144
        --prefill-max-requests 4
        --chunked-prefill-size 2048
        --model-path Qwen/Qwen3.8-27B-FP8
        --reasoning-parser qwen3
        --tool-call-parser qwen3_coder
        --quantization fp8
        --context-length 262144
        --max-mamba-cache-size 20
        --mamba-full-memory-ratio 2.29
        --speculative-algo NEXTN
        --speculative-num-steps 3
        --speculative-eagle-topk 1
        --speculative-num-draft-tokens 4
        --allow-auto-truncate
        --disable-fast-image-processor
        --limit-mm-data-per-request '{"image":1}'
        --mm-process-config '{"image":{"max_pixels":40000}}'
